###
POST http://localhost:8080/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "test@gmail.com",
  "full_name": "test",
  "role": "USER",
  "password": "12345678"
}

###
POST http://localhost:8080/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "12345678"
}

###
POST http://localhost:8080/products HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZ21haWwuY29tIiwiaWQiOjQsInJvbGUiOiJVU0VSIn0.2-hlLUk4hb-YKE7aomgMAVeIHLkBTpsh9qjiw9x08uc

{
  "title": "Test 3",
  "description": "Lorem ipsum"
}

###
GET http://localhost:8080/products HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsImlkIjoyNywicm9sZSI6IlVTRVIifQ.spjQWK4EFFlRa-zRiZdkR43-FfvJ0eiRiDKKJCbZE0k

###
GET http://localhost:8080/products/101 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZ21haWwuY29tIiwiaWQiOjQsInJvbGUiOiJVU0VSIn0.2-hlLUk4hb-YKE7aomgMAVeIHLkBTpsh9qjiw9x08uc


###
PUT http://localhost:8080/products/7 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZ21haWwuY29tIiwiaWQiOjQsInJvbGUiOiJVU0VSIn0.2-hlLUk4hb-YKE7aomgMAVeIHLkBTpsh9qjiw9x08uc

{
  "title": "Smart phone",
  "description": "Lorem ipsum sit"
}

###
DELETE http://localhost:8080/products/14 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZ21haWwuY29tIiwiaWQiOjQsInJvbGUiOiJVU0VSIn0.2-hlLUk4hb-YKE7aomgMAVeIHLkBTpsh9qjiw9x08uc