POST http://localhost:8080/users/register HTTP/1.1
Content-Type: application/x-www-form-urlencoded

email=admin@gmail.com
&full_name=Admin
&role=ADMIN
&password=12345678

### ADMIN
POST http://localhost:8080/users/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

email=admin@gmail.com
&password=12345678

### ADMIN
POST http://localhost:8080/products HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjozLCJyb2xlIjoiQURNSU4ifQ.DkCtL0NPVmZtY2RfRRtbJH7DrYZSH1f0SnQBSOCJhHk

title=Laptop
&description=Lorem ipsum

### ADMIN
GET http://localhost:8080/products HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjozLCJyb2xlIjoiQURNSU4ifQ.DkCtL0NPVmZtY2RfRRtbJH7DrYZSH1f0SnQBSOCJhHk

### ADMIN
PUT http://localhost:8080/products/1 HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjozLCJyb2xlIjoiQURNSU4ifQ.DkCtL0NPVmZtY2RfRRtbJH7DrYZSH1f0SnQBSOCJhHk

title=Smart phone
&description=Lorem ipsum.

### ADMIN
DELETE http://localhost:8080/products/5 HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjozLCJyb2xlIjoiQURNSU4ifQ.DkCtL0NPVmZtY2RfRRtbJH7DrYZSH1f0SnQBSOCJhHk

###
POST http://localhost:8080/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "user@gmail.com",
  "full_name": "user",
  "role": "USER",
  "password": "12345678"
}

###
POST http://localhost:8080/users/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

email=user@gmail.com
&password=12345678

### USER
POST http://localhost:8080/products HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZ21haWwuY29tIiwiaWQiOjQsInJvbGUiOiJVU0VSIn0.2-hlLUk4hb-YKE7aomgMAVeIHLkBTpsh9qjiw9x08uc

title=Camera
&description=Lorem ipsum

### USER
GET http://localhost:8080/products HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZ21haWwuY29tIiwiaWQiOjQsInJvbGUiOiJVU0VSIn0.2-hlLUk4hb-YKE7aomgMAVeIHLkBTpsh9qjiw9x08uc

### USER
PUT http://localhost:8080/products/4 HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZ21haWwuY29tIiwiaWQiOjQsInJvbGUiOiJVU0VSIn0.2-hlLUk4hb-YKE7aomgMAVeIHLkBTpsh9qjiw9x08uc

title=Smart phone
&description=Lorem ipsum.

### USER
DELETE http://localhost:8080/products/2 HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZ21haWwuY29tIiwiaWQiOjQsInJvbGUiOiJVU0VSIn0.2-hlLUk4hb-YKE7aomgMAVeIHLkBTpsh9qjiw9x08uc