POST http://localhost:8080/users/register HTTP/1.1
Content-Type: application/x-www-form-urlencoded

email=admin@gmail.com
&full_name=Admin
&role=ADMIN
&password=12345678

###
POST http://localhost:8080/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "user@gmail.com",
  "full_name": "user",
  "role": "USER",
  "password": "12345678"
}

###
POST http://localhost:8080/users/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

email=admin@gmail.com
&password=12345678

###
POST http://localhost:8080/products HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFyZGlAZ21haWwuY29tIiwiaWQiOjF9.DJ9K-teRTQA6GKnOzRjPkwyUL7-ZDwL4_XfgKdpfjOA

title=Phone
&description=Lorem ipsum

###
GET http://localhost:8080/products HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjozLCJyb2xlIjoiQURNSU4ifQ.DkCtL0NPVmZtY2RfRRtbJH7DrYZSH1f0SnQBSOCJhHk


###
PUT http://localhost:8080/products/1 HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFyZGlAZ21haWwuY29tIiwiaWQiOjF9.DJ9K-teRTQA6GKnOzRjPkwyUL7-ZDwL4_XfgKdpfjOA

title=Smart phone
&description=Lorem ipsum.